allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - framer-motion@12.43.0
  - motion-dom@12.43.0
  - motion@12.43.0
